default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: YOUR_USERNAME   # 자신의 DB username 입력
  password: YOUR_PASSWORD   # 자신의 DB password 입력
  host: 127.0.0.1
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tmdb_development

test:
  <<: *default
  database: tmdb_test
