default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ansdmsghks9184
  host: 127.0.0.1
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tmdb_development_smulation

test:
  <<: *default
  database: tmdb_test_smulation

  